# kubectl apply -f Service_be.yml
apiVersion: v1
kind: Service
metadata:
  name: hernan-chumpitaz-service
  namespace: hernan-chumpitaz-namespace
spec:
  type: NodePort
  ports:
  - port: 30001      
    targetPort: 8085  
    nodePort: 30001   
  selector:
    app: backend-hernan-chumpitaz-deployment  
