# kubectl apply -f Service_fe.yml
apiVersion: v1
kind: Service
metadata:
  name: hernan-chumpitaz-service
  namespace: hernan-chumpitaz-namespace
spec:
  type: NodePort
  ports:
  - port: 30002      
    targetPort: 4200  
    nodePort: 30002  
  selector:
    app: frontend-hernan-chumpitaz-deployment  
